apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app: {{ template "solr.fullname" . }}
spec:
  ports:
  - port: 8983
    name: solr
  clusterIP: None
  selector:
    app: {{ template "solr.fullname" . }}
